ARG PHP_VERSION
FROM php:$PHP_VERSION

RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  git \
  unzip \
  wget \
  zip

WORKDIR /app

COPY . .
COPY --from=composer /usr/bin/composer /usr/local/bin/composer

ARG FRANKENPHP_VERSION
RUN curl -L "https://github.com/dunglas/frankenphp/releases/tag/${FRANKENPHP_VERSION}/download/frankenphp-linux-aarch64" -o "/app/frankenphp"
RUN mv frankenphp /usr/local/bin/

RUN cp .env.example .env
RUN docker-php-ext-install sockets pcntl posix
RUN composer install --no-dev

ARG OCTANE_VERSION

RUN composer require laravel/octane:$OCTANE_VERSION
RUN php artisan key:generate
RUN php artisan octane:install --server=frankenphp

# create database & apply migrations
RUN touch database/database.sqlite && php artisan migrate --no-interaction

CMD php -d variables_order=EGPCS artisan octane:start --server=frankenphp --host=0.0.0.0 --admin-port=2019 --port=8000
